# Generated by Django 4.1 on 2022-08-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="accout_balance",
        ),
        migrations.AddField(
            model_name="user",
            name="account_balance",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
